version: 2.1

orbs:
  win: circleci/windows@5.1.1

jobs:
  # Fetches the zeek-testing test traces either from a cache or the remote host
  # and presents them in a workspace for other build jobs to use. This saves
  # other jobs from having to download them.
  fetch-test-traces:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - restore_cache:
          keys:
            - zeek-traces-v2
      - run:
          name: Initializing external testing repos
          command: ci/init-external-repos.sh
      - save_cache:
          key: zeek-traces-v2
          paths:
            - testing/external/zeek-testing-traces
      - persist_to_workspace:
          root: .
          paths:
            - testing/external/zeek-testing-traces

  linux-build:
    parameters:
      git_install:
        type: string
      docker_image:
        type: string
      deps_script:
        type: string
      resource_class:
        type: string
        default: large
      configure_flags:
        type: string
        default: --build-type=release --disable-broker-tests --prefix=${ZEEK_CI_WORKING_DIR}/install --ccache --enable-werror
      extra_env:
        type: string
        default: ""
      enable_tests:
        type: boolean
        default: true
      enable_benchmarks:
        # TODO: create the benchmarker steps
        type: boolean
        default: false
      install_spicy_analyzers:
        type: boolean
        default: false
    environment:
      ZEEK_CI: 1
      ZEEK_CI_CONFIGURE_FLAGS: << parameters.configure_flags >>
      ZEEK_CI_CPUS: 4
      ZEEK_CI_BTEST_JOBS: 4
      ZEEK_CI_BTEST_RETRIES: 2
      ZEEK_CI_RUNNER_OS: linux
      ZEEK_TEST_ULIMIT_OPEN_FILES: 256
      ZEEK_CIRCLE_EXTRA_ENV: << parameters.extra_env >>
      ZEEK_CI_CREATE_ARTIFACT: << parameters.enable_benchmarks >>
    docker:
      - image: << parameters.docker_image >>
    resource_class: << parameters.resource_class >>
    steps:
      - run:
          name: Set extra environment variables
          command: |
            echo "export ZEEK_CI_WORKING_DIR=${CIRCLE_WORKING_DIRECTORY}" >> "$BASH_ENV"
            IFS=$'\n'
            for line in ${ZEEK_CIRCLE_EXTRA_ENV}; do
              echo "export ${line}" >> "$BASH_ENV"
            done
      - run:
          name: Install git
          command: << parameters.git_install >>
      - checkout
      - run:
          name: Install dependencies
          command: << parameters.deps_script >>
      - run:
          name: Update submodules
          command: git submodule update --recursive --init
      - restore_cache:
          keys:
            - v2-ccache-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ .Branch }}-{{ .Revision }}-
            - v2-ccache-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ .Branch }}-
            - v2-ccache-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-
      - attach_workspace:
          at: .
      - run:
          name: Initialize external testing repos
          command: ci/init-external-repos.sh
      - run:
          name: Setup ccache
          command: |
            set +e
            mkdir -p ~/.ccache
            ccache --set-config=max_size=2G
            ccache --set-config=compression=true
            ccache --zero-stats
            ccache --show-stats
      - run:
          name: Build
          command: ci/build.sh
          environment:
      - run:
          name: Show ccache statistics
          command: ccache --show-stats
      - save_cache:
          key: v2-ccache-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/.ccache
      - when:
          condition: << parameters.enable_tests >>
          steps:
            - run:
                name: Test
                command: ci/test.sh
            - store_test_results:
                path: btest-results
      - when:
          condition: << parameters.install_spicy_analyzers >>
          steps:
            - run:
                name: Install spicy analyzers
                command: ci/spicy-install-analyzers.sh
      - when:
          condition: << parameters.enable_benchmarks >>
          steps:
            - store_artifacts:
                path: build.tgz
                destination: build
            - run:
                name: Run benchmarks
                command: ci/benchmark.sh

  windows-build:
    environment:
      ZEEK_CI: 1
      ZEEK_CI_CPUS: 4
      ZEEK_CI_BTEST_JOBS: 2
      ZEEK_CI_BTEST_RETRIES: 2
      ZEEK_CI_RUNNER_OS: windows
      ZEEK_CI_SKIP_EXTERNAL_BTESTS: 1
    executor:
      name: win/server-2022
      size: large
    steps:
      - run:
          name: Install Chocolatey dependencies
          command: |
            choco install -y --no-progress sed
            choco install -y --no-progress winflexbison3
            choco install -y --no-progress ccache
            choco install -y --no-progress ninja
      - run:
          name: Enable git symlinks
          command: git config --global core.symlinks true
      - checkout:
          # For some reason the default working path has stuff in it already so it can't clone into
          # that. Unfortunately that means we have to change the working directory for every other
          # command.
          path: zeek
      - run:
          name: Update submodules
          command: git submodule update --recursive --init
          working_directory: zeek
      - run:
          name: Dump environment info
          command: ci\windows\prepare.cmd
          shell: cmd.exe
          working_directory: zeek
      - restore_cache:
          name: Restore ccache
          keys:
            - v2-ccache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}
            - v2-ccache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-
            - v2-ccache-{{ .Environment.CIRCLE_JOB }}-
      - restore_cache:
          name: Restore vcpkg cache
          keys:
            - vcpkg-{{ .Branch }}-{{ .Revision }}
            - vcpkg-{{ .Branch }}-
            - vcpkg-
      - run:
          name: Setup ccache
          command: |
            mkdir C:\tmp\zeek-ccache
            ccache --set-config=max_size=2G
            ccache --set-config=compression=true
            ccache --set-config=cache_dir=C:\tmp\zeek-ccache
            ccache --zero-stats
            ccache --show-stats
      - run:
          name: Configure
          command: ci\windows\configure.cmd
          working_directory: zeek
      - save_cache:
          name: Saving vcpkg build cache
          key: vcpkg-{{ .Branch }}-{{ .Revision }}
          paths:
            - zeek\auxil\vcpkg\installed
            - zeek\auxil\vcpkg\packages
            - zeek\auxil\vcpkg\downloads
      - run:
          name: Build
          command: ci\windows\build.cmd
          working_directory: zeek
      - save_cache:
          key: v2-ccache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - C:\tmp\zeek-ccache
      - run:
          name: Test
          command: ci/windows/test.cmd
          working_directory: zeek

  macos-build:
    parameters:
      configure:
        type: string
        default: --build-type=release --disable-broker-tests --prefix=$CIRRUS_WORKING_DIR/install --ccache --enable-werror --with-krb5=/opt/homebrew/opt/krb5 -D NODEJS_ROOT_DIR=/opt/homebrew/opt/node@24
    environment:
      ZEEK_CI: 1
      ZEEK_CI_CONFIGURE_FLAGS: << parameters.configure >>
      # This is based on the size of the m4pro.medium runner, as specified in Circle's docs at
      # https://circleci.com/docs/guides/execution-managed/using-macos/#available-resource-classes.
      ZEEK_CI_CPUS: 6
      ZEEK_CI_BTEST_JOBS: 6
      ZEEK_CI_BTEST_RETRIES: 2
      ZEEK_CI_RUNNER_OS: macos
    macos:
      # TODO: should this be a parameter? Do we care to test on other Xcode versions other than the
      # latest? See https://circleci.com/docs/guides/execution-managed/using-macos/#supported-xcode-versions-silicon
      # for other options.
      xcode: 26.5.0
    resource_class: m4pro.medium
    steps:
      - run:
          name: Set extra environment variables
          command: |
            echo "export ZEEK_CI_WORKING_DIR=${CIRCLE_WORKING_DIRECTORY}" >> "$BASH_ENV"
      - checkout
      - run:
          name: Install dependencies
          command: ci/macos/prepare.sh
      - run:
          name: Update submodules
          command: git submodule update --recursive --init
      - restore_cache:
          name: Restore ccache directory
          keys:
            - v2-ccache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}
            - v2-ccache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-
            - v2-ccache-{{ .Environment.CIRCLE_JOB }}-
      - attach_workspace:
          at: .
      - run:
          name: Initialize external testing repos
          command: ci/init-external-repos.sh
      - run:
          name: Setup ccache
          command: |
            set +e
            mkdir -p ~/.ccache
            ccache --set-config=max_size=2G
            ccache --set-config=compression=true
            ccache --zero-stats
            ccache --show-stats
      - run:
          name: Build
          command: ci/build.sh
          environment:
      - run:
          name: Show ccache statistics
          command: ccache --show-stats
      - save_cache:
          name: Save ccache directory
          key: v2-ccache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/.ccache
      - run:
          name: Test
          command: ci/test.sh
      - store_test_results:
          name: Store btest results
          path: btest-results

workflows:
  # build-and-test:
  #   when:
  #     not:
  #       equal: [ "circleci-project-setup", << pipeline.git.branch >> ]
  #   jobs:
      # - windows-build
      # - linux-build:
      #     name: ubuntu-24.04
      #     git_install: apt update && apt install -y git
      #     configure: --build-type=release --disable-broker-tests --prefix=$CIRRUS_WORKING_DIR/install --ccache --enable-werror
      #     deps_script: ci/ubuntu-24.04/install_dependencies.sh
      #     docker_image: ubuntu:24.04
      # - linux-build:
      #     name: fedora-43
      #     git_install: dnf -y install git
      #     configure: --build-type=release --disable-broker-tests --prefix=$CIRRUS_WORKING_DIR/install --ccache --enable-werror
      #     deps_script: ci/fedora-43/install_dependencies.sh
      #     docker_image: fedora:43
  circleci-config-testing:
    when:
      equal: [ "circleci-project-setup", << pipeline.git.branch >> ]
    jobs:
      - fetch-test-traces
      - macos-build:
          name: macOS-xcode-26.5
          requires: [fetch-test-traces]
      - macos-build:
          name: macOS-xcode-16.4
          requires: [fetch-test-traces]
      - linux-build:
          name: alpine
          git_install: apk add --no-cache git
          deps_script: ci/alpine/install_dependencies.sh
          docker_image: alpine:latest
          requires: [fetch-test-traces]
      - linux-build:
          name: debian-12
          git_install: apt update && apt install -y git
          deps_script: ci/debian-12/install_dependencies.sh
          docker_image: debian:12
          requires: [fetch-test-traces]
      - linux-build:
          name: debian-13
          git_install: apt update && apt install -y git
          deps_script: ci/debian-13/install_dependencies.sh
          docker_image: debian:13
          requires: [fetch-test-traces]
      - linux-build:
          name: debian-13-arm
          git_install: apt update && apt install -y git
          deps_script: ci/debian-13/install_dependencies.sh
          docker_image: debian:13
          resource_class: arm.large
          requires: [fetch-test-traces]
      - linux-build:
          name: debian-13-binary
          git_install: apt update && apt install -y git
          deps_script: ci/debian-13/install_dependencies.sh
          docker_image: debian:13
          resource_class: arm.large
          configure_flags:  --prefix=$CIRRUS_WORKING_DIR/install --libdir=$CIRRUS_WORKING_DIR/install/lib --binary-package --enable-static-broker --enable-static-binpac --disable-broker-tests --build-type=Release --ccache --enable-werror
          requires: [fetch-test-traces]
      - linux-build:
          name: debian-13-static
          git_install: apt update && apt install -y git
          deps_script: ci/debian-13/install_dependencies.sh
          docker_image: debian:13
          configure_flags: --build-type=release --disable-broker-tests --enable-static-broker --enable-static-binpac --prefix=${WORKING_DIR}/install --ccache --enable-werror
          requires: [fetch-test-traces]
      - linux-build:
          name: fedora-43
          git_install: dnf install -y git
          deps_script: ci/fedora-43/install_dependencies.sh
          docker_image: fedora:43
          requires: [fetch-test-traces]
      - linux-build:
          name: fedora-44
          git_install: dnf install -y git
          deps_script: ci/fedora-44/install_dependencies.sh
          docker_image: fedora:44
          configure_flags:  --prefix=$CIRRUS_WORKING_DIR/install --libdir=$CIRRUS_WORKING_DIR/install/lib --binary-package --enable-static-broker --enable-static-binpac --disable-broker-tests --build-type=Release --ccache --enable-werror
          requires: [fetch-test-traces]
      - linux-build:
          name: opensuse-leap-16.0
          git_install: zypper refresh && zypper in -y git
          deps_script: ci/opensuse-leap-16.0/install_dependencies.sh
          docker_image: opensuse/leap:16.0
          requires: [fetch-test-traces]
      - linux-build:
          name: opensuse-tumbleweed
          git_install: zypper refresh && zypper in -y git
          deps_script: ci/opensuse-tumbleweed/install_dependencies.sh
          docker_image: opensuse/tumbleweed:latest
          requires: [fetch-test-traces]
      - linux-build:
          name: ubuntu-22.04
          git_install: apt update && apt install -y git
          deps_script: ci/ubuntu-22.04/install_dependencies.sh
          docker_image: ubuntu:22.04
          requires: [fetch-test-traces]
      - linux-build:
          name: ubuntu-24.04
          git_install: apt update && apt install -y git
          deps_script: ci/ubuntu-24.04/install_dependencies.sh
          docker_image: ubuntu:24.04
          requires: [fetch-test-traces]
          enable_benchmarks: true
      - linux-build:
          name: ubuntu-24.04-clang-libcpp
          git_install: apt update && apt install -y git
          deps_script: ci/ubuntu-24.04/install_dependencies.sh
          docker_image: ubuntu:24.04
          requires: [fetch-test-traces]
          extra_env: |
            CC="clang-19"
            CXX="clang++-19"
            CXXFLAGS="-stdlib=libc++"
            ZEEK_CI_CONFIGURE_FLAGS_EXTRA="--disable-javascript"
      - linux-build:
          name: ubuntu-24.04-clang-tidy
          git_install: apt update && apt install -y git
          deps_script: ci/ubuntu-24.04/install_dependencies.sh
          docker_image: ubuntu:24.04
          configure_flags: --build-type=debug --disable-broker-tests --prefix=$CIRRUS_WORKING_DIR/install --ccache --enable-werror --enable-clang-tidy
          requires: [fetch-test-traces]
          extra_env: |
            CC="clang-19"
            CXX="clang++-19"
          enable_tests: false
      - linux-build:
          name: ubuntu-24.04-spicy
          git_install: apt update && apt install -y git
          deps_script: ci/ubuntu-24.04/install_dependencies.sh
          docker_image: ubuntu:24.04
          configure_flags: --build-type=release --disable-broker-tests --enable-spicy-ssl --prefix=$CIRRUS_WORKING_DIR/install --ccache --enable-werror
          requires: [fetch-test-traces]
          extra_env: |
            ZEEK_CI_PREBUILD_COMMAND="cd auxil/spicy && git fetch && git reset --hard origin/main && git submodule update --init --recursive"
          install_spicy_analyzers: true
          enable_benchmarks: true
      - linux-build:
          name: ubuntu-24.04-spicy-head
          git_install: apt update && apt install -y git
          deps_script: ci/ubuntu-24.04/install_dependencies.sh
          docker_image: ubuntu:24.04
          requires: [fetch-test-traces]
          install_spicy_analyzers: true
          enable_benchmarks: true
      - linux-build:
          name: ubuntu-24.04-zam
          git_install: apt update && apt install -y git
          deps_script: ci/ubuntu-24.04/install_dependencies.sh
          docker_image: ubuntu:24.04
          requires: [fetch-test-traces]
          extra_env: |
            ZEEK_CI_SKIP_UNIT_TESTS=1
            ZEEK_CI_SKIP_EXTERNAL_BTESTS=1
            ZEEK_CI_BTEST_EXTRA_ARGS="-a zam"
            ZEEK_CI_BTEST_JOBS=3
      - linux-build:
          name: ubuntu-26.04
          git_install: apt update && apt install -y git
          deps_script: ci/ubuntu-26.04/install_dependencies.sh
          docker_image: ubuntu:26.04
          requires: [fetch-test-traces]
#      - windows-build
